var text = {
  "zhenyu_intro_name":"Zhenyu(Jason) Han",
  "zhenyu_intro_animation_name":"As you know, my name is Zhenyu Han, you can call me Jason",
  "zhenyu_intro_animation_address":"Right now, I am living at 48 Derby St, MA, 02453",
  "zhenyu_intro_animation_email":"you can contact me at hanzhenyu@brandeis.edu",
  "zhenyu_intro_aniamtion_phone":"or through phone: 617-669-8663",
  "zhenyu_intro_aniamtion_job_description":"I am looking for a job, like: ",
  "zhenyu_intro_job_1":"ROR - Ruby on Rails developer",
  "zhenyu_intro_job_2":"UI - UI programmer",
  "zhenyu_intro_job_3":"Others - I am willing to retrain",
  "zhenyu_intro_job_info":"it would be great if your company is E-verfied for OPT extention，and also willing to sponser me the H1B visa",
  "zhenyu_intro_job_conclusion":"If you are interested, please don't be hesitated and email me or call me please.",
  "zhenyu_intro_title":"intro",
  "zhenyu_education_title":"education",
  "zhenyu_education_animation_bachelor":"I was first a CS student at NUIST (Nanjing University of Information sufficiently & Technology), then I transfer to UNCP (University of North Carolina at Pemrboke) and get Bachelor's Degree (BS) from both unveristies.",
  "zhenyu_education_animation_unist":"NUIST: 2009-2011 & 2013-2014, majoring in computer science",
  "zhenyu_education_animation_uncp":"UNCP: 2011-2013, majoring in computer science",
  "zhenyu_education_animation_master":"In 2015, I decided to take further study and spend one and half year in Brandeis, I got my master degree in May, 2016.",
  "zhenyu_education_animation_brandeis":"Brandeis: Jan, 2015 - May, 2016, majoring in computer science",
  "zhenyu_education_animation_course_total":"Here are some courses taken in Brandeis:",
  "zhenyu_education_animation_course_1":"Information Retrieval - ends with a project call ElastiCity",
  "zhenyu_education_animation_course_2":"Here are some courses taken in Brandeis:",
  "zhenyu_experience_title":"experience",
  "zhenyu_projects_title":"projects",
  "zhenyu_porojects_1":"Abbott Informatics",
  "zhenyu_porojects_2":"VCE Vrack",
  "zhenyu_porojects_3":"Landing page for KAON",
  "zhenyu_porojects_4":"CDW Integrated IT Solutions",
  "zhenyu_porojects_5":"Hycor Illustration Page",
  "zhenyu_porojects_6":"3D Billiards",
  "zhenyu_porojects_7":"IMDB for CS - ROR",
  "zhenyu_porojects_8":"Independent Study",
  "zhenyu_porojects_9":"PhotoDiary",
  "zhenyu_porojects_10":"NanoTwitter",
  "zhenyu_porojects_11":"ElastiCity",
}
